### PR TITLE
Solved Meeting Leave Crash

### PR DESCRIPTION
**Pull request by gautambitious**
Updated handleMeetingLeaveThreshhold

### CODE REVIEW

**Review by TobiasPankner — CHANGES_REQUESTED** [review]
Remove the unecessary format changes

**Comment by gautambitious** [comment]
I've removed the format changes. They had automatically been added by VS Code.

**Comment by TobiasPankner** [comment]
How does this fix a crash? Did you test it?

**Comment by gautambitious** [comment]
I tested it. The 'if statement' was not working before and was causing the else part to crash. This fixes that.

**Comment by TobiasPankner** [comment]
I tested it and it did not make any difference, crashing on hangup should be fixed with commit 11f4f7e

**Pull request closed without merging**
