### PR TITLE
Add support for blacklisting calendar meetings by their title

### PR DESCRIPTION
**Pull request by a1batross**
Useful if you have planned meetings that may (or may not) have formatted title that can be checked with simple regular expression.

Left this as WIP, because I will be able to test it only tomorrow in real situation. ;)

### CODE REVIEW

**Comment by TobiasPankner** [comment]
Very good contribution. Tell me when you have tested it and I will merge it. Thank you

**Comment by a1batross** [comment]
The only problem for now is the annoying log:

```
[15:45:33] Looking for new meetings
Found meetings:
        Group 1A from 3:00 PM to 4:30 PM 1602161940 [Calendar] [BLACKLISTED]
Blacklisted calendar meeting Group 1A from 3:00 PM to 4:30 PM, skipping...

[15:46:33] Looking for new meetings
Found meetings: 
        Group 1A from 3:00 PM to 4:30 PM 1602161940 [Calendar] [BLACKLISTED]
Blacklisted calendar meeting Group 1A from 3:00 PM to 4:30 PM, skipping...

[15:47:33] Looking for new meetings
Found meetings: 
        Group 1A from 3:00 PM to 4:30 PM 1602161940 [Calendar] [BLACKLISTED]
Blacklisted calendar meeting Group 1A from 3:00 PM to 4:30 PM, skipping...
```

I'm not sure how to make it remember that we already not going to join that meeting yet.

**Comment by TobiasPankner** [comment]
I would just not print the "skipping..." line as there already is the [BLACKLISTED] above.

**Comment by TobiasPankner** [comment]
And how does it handle if the newest meeting is blacklisted? Does it join the next newest one or does it not join anything?

**Comment by TobiasPankner** [comment]
Yeah, that is pretty confusing. Maybe I should add some comments haha.  
What the decide_meeting function does is order the meetings by the start time. After that, it gets the time of the newest meeting. Then it puts only the meetings in a new list that have an equal or later start time (this is the loop).  This is pretty weird and there is most certainly a better way of doing it.  
You could filter out the blacklisted meeting above this line:  
https://github.com/a1batross/Teams-Auto-Joiner/blob/33503c0ef04c68953f7eac683166a7c59abe0bcd/auto_joiner.py#L342  
then it would just join the newest, non blacklisted, meeting.

**Comment by a1batross** [comment]
Sorry, forgot to commit a fix. 

It works for me now as intended.

**Pull request merged**
